version: "3.9"

services:
  node:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  node_modules:
  yarn-cache:
